#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/msgdlg.h>
#include "wx/dirdlg.h"
#include <wx/dir.h>

//// end generated include
class Point
{
public:
	Point(int xUpLeft, int yUpLeft, int xDownRight, int yDownRigth)
		: _xUpLeft(xUpLeft), _yUpLeft(yUpLeft), _xDownRight(xDownRight), _yDownRigth(yDownRigth) {}
	~Point() = default;
	int _xUpLeft;
	int _yUpLeft;
	int _xDownRight;
	int _yDownRigth;
};


/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
		wxArrayString path_array;
		size_t file_count;
		wxImage* m_imageRGB;
		wxBitmap m_imageBitmap;
		int windowWidth;
		int windowHeight;
		bool imageLoaded;
		int m_imageWidth;
		int m_imageHeight;
		int m_imageCounter;
		int m_fullImagesWidth;
		int m_fullImagesHeight;
		unsigned char* m_myImage;
		
		std::map<int, Point> imagesPosition;
		void repaint();
		//// end generated class members
protected:

	void WindowOnSize(wxSizeEvent& event);
	void WindowUpdate(wxUpdateUIEvent& event);
	void LoadImgOnClick(wxCommandEvent& event);



};

#endif // __GUIMyFrame1__
